### ISSUE TITLE
Ctrl+Backspace doesn't show properly in replays. 

### ISSUE THREAD

**Issue by SylveonBottle** [StephenHaney/dear-diary-ai#20]
https://deardiary.ai/entry/FcNhm1Al5VfrZ2fMohIM
Backspaces work properly, so why not Ctrl+backspace?

https://user-images.githubusercontent.com/17802843/126122118-8c86cbe1-1462-42af-9f15-880c4792222f.mp4

**Comment by StephenHaney** [comment]
Thanks for the report! We ignore certain modifier keys to avoid playing sounds when you perform OS keyboard operations. `ctrl+backspace` seems to be getting caught in there. I'll take a look at this next time I play around with the key logic.
